spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:3306/${DB_NAME:momentum}
    username: ${DB_USER:momentum}
    password: ${DB_PASSWORD:momentum}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      initialization-fail-timeout: -1
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
